name: pegasus_void
description: Pegasus Void - Device Controller
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_background_service: ^5.0.10
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  vibration: ^2.0.0
  flutter_local_notifications: ^17.2.1
  workmanager: ^0.5.2
  torch_light: ^1.0.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.txt
    - assets/fonts/
  fonts:
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
